import * as random from '../random.js';
describe('template spec', () => {
  it('passes', () => {
    //เข้าเว็บและล็อคอิน
    cy.visit('https://vch-dev.smoothdark.com/en/applicant')
    cy.get('#email_login').type('saurabh@smoothgraph.in')
    cy.get('#password').type('123456')
    cy.get('#btn_login_email').click('')
    cy.get('[href="https://vch-dev.smoothdark.com/en/applicant/medical/job-list"]').click()
    cy.get('.date-btn-wrap > .btn').click()
    cy.get(':nth-child(2) > :nth-child(1) > .input-group > .form-control').type(random.number(5))
    cy.get(':nth-child(2) > .date-picker').click()
    cy.wait(1000)
    cy.get('.arrowTop > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-days > .dayContainer > .today').click()
    cy.get('#salutation').select('Doctor Woman')
    cy.get(':nth-child(3) > .box-content > :nth-child(2) > :nth-child(1) > input').type((random.string_eng(5)))
    cy.get(':nth-child(3) > .box-content > :nth-child(2) > :nth-child(2) > input').type((random.string_eng(5)))
    cy.get(':nth-child(3) > .col-md-6 > input').type((random.string_eng(5)))
    cy.get('.flatpicker').click()
    cy.wait(1000)
    cy.get('.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-days > .dayContainer > .today').click()
    cy.get('.box-content > :nth-child(4) > :nth-child(2) > input').type(random.number(2))
    cy.get(':nth-child(5) > :nth-child(1) > .input-group > .form-control').type(random.number(3))
    cy.get(':nth-child(2) > .input-group > .form-control').type(random.number(2))
    cy.get('.col-md-6.input-group > input').type(random.number(13))
    cy.get('.select_country > [type="text"]').type(random.number(10))
    cy.get('#inlineFormInputGroup').type('email@email')
    cy.get(':nth-child(8) > .form-group > :nth-child(2) > .radio-label').click()
    cy.get(':nth-child(9) > .col-md-12 > input').type((random.string_eng(20)))
    cy.get(':nth-child(4) > .box-content > :nth-child(1) > .form-row > :nth-child(1) > input').type('ABC University')
    cy.get(':nth-child(4) > .box-content > :nth-child(1) > .form-row > :nth-child(2) > input').type('Doctor')
    cy.get(':nth-child(4) > .box-content > :nth-child(1) > .form-row > :nth-child(3) > input').type('Medical')
    cy.get(':nth-child(1) > .form-row > :nth-child(4) > .date-picker').click()
    cy.wait(1000)
    cy.get('.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-days > .dayContainer > .today').click()
    cy.get(':nth-child(4) > .box-content > :nth-child(1) > .form-row > :nth-child(5) > input').type(random.number(1) + '.' + random.number(2))
    cy.get('.box-content > :nth-child(2) > .form-row > :nth-child(1) > input').type('ABC School')
    cy.get('.box-content > :nth-child(2) > .form-row > :nth-child(2) > input').type('Doctor')
    cy.get(':nth-child(2) > .form-row > :nth-child(3) > input').type('Medical')
    cy.get(':nth-child(2) > .form-row > :nth-child(4) > .date-picker').click()
    cy.wait(1000)
    cy.get('.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-days > .dayContainer > .today').click()
    cy.get(':nth-child(2) > .form-row > :nth-child(5) > input').type(random.number(1) + '.' + random.number(2))
    cy.get(':nth-child(3) > .form-row > :nth-child(1) > input').type('ABC University')
    cy.get(':nth-child(3) > .form-row > :nth-child(2) > input').type('Doctor')
    cy.get(':nth-child(3) > .form-row > :nth-child(3) > input').type('Medical')
    cy.get(':nth-child(3) > .form-row > :nth-child(4) > .date-picker').click()
    cy.wait(1000)
    cy.get('.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-days > .dayContainer > .today').click()
    cy.get(':nth-child(3) > .form-row > :nth-child(5) > input').type(random.number(1) + '.' + random.number(2))
    cy.get(':nth-child(4) > .form-row > :nth-child(1) > input').type('ABC University')
    cy.get(':nth-child(4) > .form-row > :nth-child(2) > input').type('Doctor')
    cy.get(':nth-child(4) > .form-row > :nth-child(3) > input').type('Medical')
    cy.get(':nth-child(4) > .form-row > :nth-child(4) > .date-picker').click()
    cy.wait(1000)
    cy.get('.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-days > .dayContainer > .today').click()
    cy.get(':nth-child(4) > .form-row > :nth-child(5) > input').type(random.number(1) + '.' + random.number(2))
  })
})